services:
    terminal42.folderpage.dcamanager:
        class: Terminal42\FolderpageBundle\DcaManager
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@request_stack'
            - '@session'
            - '@router'
            - '@security.token_storage'
